# Generated by Django 2.2.3 on 2022-12-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_usuario', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_usuario', models.IntegerField(null=True)),
                ('nombre_usuario', models.CharField(max_length=64, null=True)),
                ('email_usuario', models.CharField(max_length=64, null=True)),
                ('direccion_usuario', models.CharField(max_length=64, null=True)),
                ('contrasena_usuario', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
