# Generated by Django 3.2.16 on 2022-12-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usmelectrica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_cliente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_cliente', models.IntegerField(null=True)),
                ('nombre_cliente', models.CharField(max_length=64, null=True)),
                ('email_cliente', models.CharField(max_length=64, null=True)),
                ('direccion_cliente', models.CharField(max_length=64, null=True)),
                ('contrasena_cliente', models.CharField(max_length=24, null=True)),
                ('estado_cliente', models.BooleanField(default=True)),
                ('tipo_cliente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='Natural', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id_gerente', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_gerente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_gerente', models.IntegerField(null=True)),
                ('nombre_gerente', models.CharField(max_length=64, null=True)),
                ('email_gerente', models.CharField(max_length=64, null=True)),
                ('direccion_gerente', models.CharField(max_length=64, null=True)),
                ('contrasena_gerente', models.CharField(max_length=24, null=True)),
                ('estado_gerente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_operador', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_operador', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_operador', models.IntegerField(null=True)),
                ('nombre_operador', models.CharField(max_length=64, null=True)),
                ('email_operador', models.CharField(max_length=64, null=True)),
                ('direccion_operador', models.CharField(max_length=64, null=True)),
                ('contrasena_operador', models.CharField(max_length=24, null=True)),
                ('estado_operador', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='celular_usuario',
            new_name='celular_admin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='contrasena_usuario',
            new_name='contrasena_admin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='direccion_usuario',
            new_name='direccion_admin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='email_usuario',
            new_name='email_admin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='id_usuario',
            new_name='id_admin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='nombre_usuario',
            new_name='nombre_admin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='tipo_id_usuario',
            new_name='tipo_id_admin',
        ),
    ]
