# Generated by Django 3.2.16 on 2022-12-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usmelectrica', '0002_auto_20221217_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
