# Generated by Django 3.2.16 on 2022-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usmelectrica', '0003_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_id_cliente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='C.C', max_length=12)),
                ('celular_cliente', models.IntegerField(null=True)),
                ('nombre_cliente', models.CharField(max_length=64, null=True)),
                ('email_cliente', models.CharField(max_length=64, null=True)),
                ('direccion_cliente', models.CharField(max_length=64, null=True)),
                ('contrasena_cliente', models.CharField(max_length=24, null=True)),
                ('estado_cliente', models.BooleanField(default=True)),
                ('tipo_cliente', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='Natural', max_length=12)),
            ],
        ),
    ]
