# Generated by Django 3.2.16 on 2022-12-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usmelectrica', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_factura', models.IntegerField()),
                ('lectura_factura', models.IntegerField()),
                ('total_factura', models.IntegerField()),
                ('date_crea_factu', models.DateField()),
                ('date_ven_factu', models.DateField()),
                ('periodo_factu', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellidoM_admin',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellidoP_admin',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoM_Cliente',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoP_Cliente',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gerente',
            name='apellidoM_Gerente',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gerente',
            name='apellidoP_Gerente',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='apellidoM_Operador',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='apellidoP_Operador',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicios', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], default='Residencial', max_length=12)),
                ('estado_servicio', models.BooleanField(default=True)),
                ('mora_servicio', models.BooleanField(default=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('forma_pago', models.CharField(choices=[('Presencial', 'Presencial'), ('Banco', 'Banco'), ('Virtual', 'Virtual')], default='Presencial', max_length=12)),
                ('total_pago', models.IntegerField()),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.factura')),
                ('operador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.operador')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usmelectrica.servicio'),
        ),
    ]
